import { useState, useEffect, useMemo } from 'react';
import { Link } from 'react-router-dom';
import { Calendar, Download, CreditCard, RefreshCw, AlertTriangle, Clock, CheckCircle } from 'lucide-react';
import { Layout } from '@/components/Layout';
import { differenceInDays, format, addDays } from 'date-fns';

interface Booking { id: string; hostel_name: string; hostel_image: string; room_type: string; address: string; ref: string; status: 'active' | 'upcoming' | 'past'; move_in_date: string; move_out_date: string; total_amount: number; paid_amount: number; balance: number; payment_plan: 'full' | 'installment'; installments: { number: number; amount: number; due_date: string; status: 'paid' | 'pending' }[]; grace_period: number; }

const mockBookings: Booking[] = [
  { id: '1', hostel_name: 'Green View Hostel', hostel_image: '/hostel-ext-1.jpg', room_type: 'Self-contained', address: '15 Akoka Road, Yaba', ref: 'WH-2026-001', status: 'active', move_in_date: '2026-01-15', move_out_date: '2027-01-14', total_amount: 165000, paid_amount: 112200, balance: 52800, payment_plan: 'installment', installments: [{ number: 1, amount: 56100, due_date: '2026-01-15', status: 'paid' }, { number: 2, amount: 13200, due_date: '2026-04-15', status: 'paid' }, { number: 3, amount: 13200, due_date: '2026-07-15', status: 'pending' }, { number: 4, amount: 13200, due_date: '2026-10-15', status: 'pending' }], grace_period: 10 },
  { id: '2', hostel_name: 'Campus Heights', hostel_image: '/hostel-room-1.jpg', room_type: 'Single Room', address: '32 Bodija Estate, Ibadan', ref: 'WH-2026-002', status: 'upcoming', move_in_date: '2026-09-01', move_out_date: '2027-08-31', total_amount: 220000, paid_amount: 0, balance: 220000, payment_plan: 'full', installments: [], grace_period: 10 },
];

function StayProgress({ moveIn, moveOut, gracePeriod }: { moveIn: string; moveOut: string; gracePeriod: number }) {
  const [now, setNow] = useState(new Date());
  useEffect(() => { const interval = setInterval(() => setNow(new Date()), 60000); return () => clearInterval(interval); }, []);
  const moveInDate = new Date(moveIn); const moveOutDate = new Date(moveOut); const totalDays = differenceInDays(moveOutDate, moveInDate); const daysElapsed = differenceInDays(now, moveInDate); const daysRemaining = differenceInDays(moveOutDate, now); const progress = Math.max(0, Math.min(100, (daysElapsed / totalDays) * 100));
  const alerts = useMemo(() => { const a = []; if (daysRemaining <= 7 && daysRemaining > 0) a.push({ days: 7, severity: 'critical' as const }); else if (daysRemaining <= 15) a.push({ days: 15, severity: 'warning' as const }); else if (daysRemaining <= 30) a.push({ days: 30, severity: 'caution' as const }); else if (daysRemaining <= 90) a.push({ days: 90, severity: 'info' as const }); return a; }, [daysRemaining]);
  return (<div><div className="flex items-center justify-between mb-2"><h3 className="text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>Stay Progress</h3>{daysRemaining > 0 ? <span className="text-xs" style={{ color: 'var(--accent-secondary)' }}><Clock size={12} className="inline" /> {daysRemaining} days remaining</span> : <span className="text-xs" style={{ color: 'var(--accent-primary)' }}><AlertTriangle size={12} className="inline" /> Grace period active</span>}</div><div className="h-2 rounded-full overflow-hidden mb-2" style={{ background: 'var(--border-light)' }}><div className="h-full rounded-full transition-all duration-500" style={{ width: `${progress}%`, background: 'linear-gradient(90deg, var(--accent-secondary), var(--accent-tertiary))' }} /></div><div className="flex justify-between text-xs mb-3" style={{ color: 'var(--text-muted)' }}><span>{format(moveInDate, 'MMM d, yyyy')}</span><span>{format(moveOutDate, 'MMM d, yyyy')}</span></div><p className="text-xs" style={{ color: 'var(--text-muted)' }}>Grace period: {gracePeriod} days (Standard)</p>{alerts.length > 0 && <div className="flex flex-wrap gap-2 mt-2">{alerts.map(a => <span key={a.days} className="inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-medium animate-pulse-glow" style={{ background: a.severity === 'critical' ? '#fce4ec' : a.severity === 'warning' ? '#fff3e0' : a.severity === 'caution' ? '#fffde7' : '#e8f5e9', color: a.severity === 'critical' ? '#c62828' : a.severity === 'warning' ? '#ef6c00' : a.severity === 'caution' ? '#f9a825' : '#2e7d32' }}><AlertTriangle size={10} /> {a.days} days left</span>)}</div>}</div>);
}

export default function Bookings() {
  const [activeTab, setActiveTab] = useState<'active' | 'upcoming' | 'past'>('active');
  const filtered = mockBookings.filter(b => b.status === activeTab);
  return (
    <Layout>
      <div className="max-w-[1440px] mx-auto px-4 lg:px-8 py-8">
        <h1 className="text-2xl lg:text-4xl font-bold mb-6" style={{ fontFamily: 'var(--font-display)', color: 'var(--text-primary)' }}>My Bookings</h1>
        <div className="flex gap-2 mb-8">
          {(['active', 'upcoming', 'past'] as const).map(tab => <button key={tab} onClick={() => setActiveTab(tab)} className="px-5 py-2 rounded-full text-sm font-medium capitalize transition-all" style={{ background: activeTab === tab ? 'var(--text-primary)' : 'var(--bg-elevated)', color: activeTab === tab ? 'white' : 'var(--text-secondary)' }}>{tab}</button>)}
        </div>
        {filtered.length === 0 ? <div className="text-center py-20"><Calendar size={48} className="mx-auto mb-4" style={{ color: 'var(--text-muted)' }} /><h3 className="text-lg font-semibold mb-2">No {activeTab} bookings</h3><Link to="/hostels" className="btn-primary inline-block mt-4">Browse Hostels</Link></div> : <div className="space-y-6">{filtered.map(booking => (<div key={booking.id} className="card-wehouse"><div className="grid lg:grid-cols-[200px_1fr_300px] gap-6"><img src={booking.hostel_image} alt={booking.hostel_name} className="w-full h-[150px] lg:h-full object-cover rounded-xl" /><div><div className="flex items-center gap-2 mb-1"><h3 className="font-semibold">{booking.hostel_name}</h3><span className="px-2 py-0.5 rounded-full text-xs" style={{ background: 'var(--bg-elevated)', color: 'var(--text-secondary)' }}>{booking.room_type}</span></div><p className="text-xs mb-1" style={{ color: 'var(--text-secondary)' }}>{booking.address}</p><p className="text-xs mb-3" style={{ color: 'var(--text-muted)' }}>Ref: {booking.ref}</p><span className="status-available capitalize">{booking.status}</span>{booking.payment_plan === 'installment' && (<div className="mt-4"><p className="text-sm font-medium mb-2">Payment Timeline</p><div className="relative pl-4"><div className="absolute left-1.5 top-0 bottom-0 w-px" style={{ background: 'var(--border-light)' }} />{booking.installments.map((inst, i) => (<div key={i} className="relative flex items-center gap-3 mb-2"><div className="absolute -left-4 w-3 h-3 rounded-full border-2" style={{ background: inst.status === 'paid' ? 'var(--accent-secondary)' : 'white', borderColor: inst.status === 'paid' ? 'var(--accent-secondary)' : 'var(--border-medium)' }} /><span className="text-xs">#{inst.number}: ₦{inst.amount.toLocaleString()}</span>{inst.status === 'paid' ? <CheckCircle size={14} style={{ color: 'var(--accent-secondary)' }} /> : <Clock size={14} style={{ color: 'var(--accent-tertiary)' }} />}</div>))}</div><p className="text-sm font-semibold mt-2" style={{ color: 'var(--accent-primary)' }}>Remaining: ₦{booking.balance.toLocaleString()}</p></div>)}</div>{booking.status === 'active' && <StayProgress moveIn={booking.move_in_date} moveOut={booking.move_out_date} gracePeriod={booking.grace_period} />}</div><div className="flex flex-wrap gap-3 mt-6 pt-4" style={{ borderTop: '1px solid var(--border-light)' }}><Link to={`/hostels/${booking.id}`} className="btn-outline py-2 px-4 text-xs">View Details</Link>{booking.balance > 0 && <Link to="/payments" className="btn-primary py-2 px-4 text-xs flex items-center gap-1"><CreditCard size={14} /> Make Payment</Link>}<button className="flex items-center gap-1 px-4 py-2 rounded-xl border text-xs font-medium"><RefreshCw size={14} /> Request Renewal</button><button className="flex items-center gap-1 px-4 py-2 text-xs font-medium" style={{ color: 'var(--accent-primary)' }}><Download size={14} /> Receipt</button></div></div>))}</div>}
      </div>
    </Layout>
  );
}
